version: '3'

tasks:
  build:
    desc: Build lottery-tlog for all platforms
    cmds:
      - mkdir -p release
      - GOOS=linux GOARCH=amd64 go build -o release/lottery-tlog-linux-amd64 .
      - GOOS=linux GOARCH=arm64 go build -o release/lottery-tlog-linux-arm64 .
      - GOOS=darwin GOARCH=amd64 go build -o release/lottery-tlog-darwin-amd64 .
      - GOOS=darwin GOARCH=arm64 go build -o release/lottery-tlog-darwin-arm64 .
      - GOOS=windows GOARCH=amd64 go build -o release/lottery-tlog-windows-amd64.exe .

  build-oracle:
    desc: Build lottery-tlog-oracle (Oracle backend) with pure Go driver
    cmds:
      - mkdir -p release
      - go build -tags oracle -o release/lottery-tlog-oracle .

  build-oracle-all:
    desc: Build lottery-tlog-oracle for all platforms (no CGO required)
    cmds:
      - mkdir -p release
      - GOOS=linux GOARCH=amd64 go build -tags oracle -o release/lottery-tlog-oracle-linux-amd64 .
      - GOOS=linux GOARCH=arm64 go build -tags oracle -o release/lottery-tlog-oracle-linux-arm64 .
      - GOOS=darwin GOARCH=amd64 go build -tags oracle -o release/lottery-tlog-oracle-darwin-amd64 .
      - GOOS=darwin GOARCH=arm64 go build -tags oracle -o release/lottery-tlog-oracle-darwin-arm64 .
      - GOOS=windows GOARCH=amd64 go build -tags oracle -o release/lottery-tlog-oracle-windows-amd64.exe .

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: Remove built binaries
    cmds:
      - rm -rf release
